---
title: "Baseball"
---
	
Baseball has been a part of my life for as long as I can remember. Like a lot of kids, I played in Little League, collected baseball cards, and practiced switch-hitting while playing Wiffleball in the backyard. I played through high school, and more recently in men's leagues on Long Island and in Central Park. 

I was lucky enough to work for the [New York Mets](http://mets.com) as their Statistical Analyst for 8.5 years. During that time our department took huge strides in terms of its ability to collect, process, disseminate, and understand statistical data. 

In 2012, I was selected by the Mets be their representative in the [Baseball IQ](http://mlb.mlb.com/network/promotions/BBIQ.jsp) trivia show on the MLB Network. At stake was up to $45,000 for our chosen charity, [Welcome Back Veterans](http://web.welcomebackveterans.org/). Here's how I did in: 

#. [Round 1](http://mlb.mlb.com/video/play.jsp?content_id=20071689&c_id=mlb) vs. the Phillies (original air date: January 24th, 2012)
#. [Round 2](http://mlb.mlb.com/video/play.jsp?content_id=20095243&topic_id=7417714&c_id=mlb&tcid=vpp_copy_20095243&v=3) vs. the Braves (original air date: February 14th, 2012)
#. [Quarterfinals](http://mlb.mlb.com/video/play.jsp?content_id=20104291&topic_id=7417714&c_id=mlb&tcid=vpp_copy_20104291&v=3) vs. the Cubs (original air date: February 22nd, 2012)
#. [Semifinals](http://mlb.mlb.com/video/play.jsp?content_id=20105789&topic_id=7417714&c_id=mlb&tcid=vpp_copy_20105789&v=3) vs. the White Sox (original air date: February 23rd, 2012)
#. [Finals](http://mlb.mlb.com/video/play.jsp?content_id=20105791&topic_id=7417714&c_id=mlb&tcid=vpp_copy_20105791&v=3) vs. the Angels (original air date: February 23rd, 2012)


I've collected [links to some articles](press.html) in which you will find more information about my work with the Mets. 
