---
title: "Press"
---

In the interest of shameless self-promotion, here is a list of articles that mention me in some form or another:

* Goldscheider, Eric. "<a href="http://alumnae.smith.edu/?smithstories=wrestling-with-data">'Wrestling with Data'</a>." <cite>Smith Alumnae Quarterly</cite>. 17 March 2014. 
* Weld, Eric. "<a href="http://www.smith.edu/news/new-book-analyzes-baseball-analytics/">New Book Analyzes Baseball Analytics</a>." <cite>Grecourt Gate</cite>. 27 January 2014.
* Peck, Don. "<a href="http://www.theatlantic.com/magazine/archive/2013/12/theyre-watching-you-at-work/354681/">They're Watching You at Work</a>." <cite>The Atlantic</cite>. 20 November 2013.
* Rubin, Adam. "<a href="http://espn.go.com/blog/new-york/mets/post/_/id/46747/in-depth-amazin-stat-analysis-roots">In-depth: Amazin' stat analysis roots</a>." <cite>ESPN New York</cite>. 29 May 2012.
* Rubin, Adam. "<a href="http://espn.go.com/blog/new-york/mets/post/_/id/46665/stat-guru-baumer-leaving-mets-to-teach">Stat guru Baumer leaving Mets to teach</a>." <cite>ESPN New York</cite>. 28 May 2012.
* Rubin, Adam. "<a href="http://espn.go.com/blog/new-york/mets/post/_/id/38567/mets-morning-briefing-2-24-12">Mets morning briefing 2.24.12</a>." <cite>ESPN New York</cite>. 24 February 2012.
* DiGiovanna, Mike. "<a href="http://www.latimes.com/sports/sportsnow/la-angels-demmitt-wins-mlb-network-game-show-20120223,0,5789901.story?track=rss">Angels' Shane Demmitt wins MLB Network trivia show</a>." <cite>The Los Angeles Times</cite>. 23 February 2012.
* BP Staff. "<a href="http://www.baseballprospectus.com/chat/chat.php?chatId=823">Chat: Paul DePodesta</a>." <cite>Baseball Prospectus</cite>. 22 March 2011.
* Staff. "<a href="http://www.cuny.edu/news/publications/cunymatters/summer2010/for-top-players.html">For Top Players, Mets Count on Him</a>." <cite>CUNY Matters</cite>. Summer 2010.
* Vrentas, Jenny. "<a href="http://www.nj.com/mets/index.ssf/2010/04/mets_statistical_analyst_has_s.html">Mets statistical analyst has seen growth and evolution of sabermetrics in MLB</a>." <cite>The Star-Ledger</cite>. 23 April 2010 
* Sanders, Laura. "<a href="http://www.sciencenews.org/view/generic/id/46213/title/Baseball_by_the_numbers">Baseball By The Numbers</a>." <cite>Science News</cite>. Vol. 176, Number 5. 29 August 2009.  
* Miller, Dan. "<a href="http://www.qgazette.com/news/2009-06-03/Sports/006.html">Mets Help Launch Math Education Program</a>." <cite>The Queens Gazette</cite>. 3 June 2009.
* McGalliard, Gina. "<a href="http://ucsdmag.ucsd.edu/magazine/vol6no2/class/featnote3.htm">Member Spotlight</a>." <cite>@UCSD</cite>. May 2009. 
* Smith, Gary. "<a href="http://sportsillustrated.cnn.com/2007/baseball/mlb/06/12/minaya0618/">The Story of O</a>." <cite>Sports Illustrated. 18 June 2007</cite>. 
* Kernan, Kevin. "<a href="http://www.nypost.com/seven/03182007/sports/mets/all_the_gms_men_mets_kevin_kernan.htm?page=0">All the GM's Men</a>." <cite>The New York Post</cite>. 18 March 2007.
* Altamari, Daniela. "<a href="http://pqasb.pqarchiver.com/courant/access/998214991.html?dids=998214991:998214991&FMT=ABS&FMTS=ABS:FT&type=current&date=Mar+6%2C+2006&author=DANIELA+ALTIMARI&pub=Hartford+Courant&edition=&startpage=B.1&desc=WESLEYAN+GRADS+EXCEL+--+BUT+IN+PROFESSIONAL+SPORTS%3F+">Wesleyan Grads Excel - But In Professional Sports?</a>", <cite>The Hartford Courant</cite>. 6 March 2006.
* Mahler, Jonathan. "<a href="http://www.nytimes.com/2005/07/31/magazine/31METS.html?pagewanted=3&ei=5090&en=af84e2fa3c22d1ce&ex=1280462400&partner=rssuserland&emc=rss">Building the Béisbol Brand</a>." <cite>The New York Times Magazine</cite>. 31 July 2005.
* Farber, Michael. "<a href="http://www.sportsillustrated.cnn.com/2004/magazine/03/29/mets/">SI Scouting Report: New York Mets</a>." <cite>Sports Illustrated</cite>. 5 April 2004.
* Hermoso, Rafael. "<a href="http://select.nytimes.com/gst/abstract.html?res=F7091FF7395D0C728EDDA80894DC404482">Baseball; Piazza Optimistic about Playing First Base</a>." <cite>The New York Times</cite>. 21 January 2004.
* Czerwinski, Kevin. "<a href="http://www.mlb.com/news/article.jsp?ymd=20040120&content_id=629507&vkey=news_nym&fext=.jsp&c_id=nym">Roberts to Compete for Fifth Starter</a>." <cite>MLB.com</cite>. 20 January 2004.
* Blum, Ronald. "<a href="http://sports.espn.go.com/espn/wire?section=mlb&id=1713721">Mets Complete Agreement with Garcia</a>." <cite>Associated Press Archive</cite>. 20 January 2004.

